package git

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
)

// HookType represents the type of git hook.
type HookType string

const (
	PrepareCommitMsg HookType = "prepare-commit-msg"
	CommitMsg        HookType = "commit-msg"
)

// InstallHook installs a git hook that calls git-message.
// hookDir is typically .git/hooks or a global hooks directory.
// binaryPath is the absolute path to the gud binary, resolved at install time.
func InstallHook(hookDir string, hookType HookType, binaryPath string) error {
	hookPath := filepath.Join(hookDir, string(hookType))

	content := buildHookScript(binaryPath)

	//nolint:gosec // git hooks must be executable for git to invoke them
	if err := os.WriteFile(hookPath, []byte(content), 0755); err != nil {
		return fmt.Errorf("failed to write hook file: %w", err)
	}

	slog.Debug("installed hook", "path", hookPath, "type", hookType)
	return nil
}

// buildHookScript creates the hook script content using the full binary path
// so the hook works even if the binary is not on $PATH.
// The binary path is single-quoted and embedded single quotes are escaped
// to prevent shell injection via malicious binary paths.
func buildHookScript(binaryPath string) string {
	escaped := strings.ReplaceAll(binaryPath, "'", "'\\''")
	return `#!/bin/sh
# Auto-generated by gud
# Generates commit message based on staged changes

'` + escaped + `' hook run "$1"
`
}

// UninstallHook removes a git hook.
func UninstallHook(hookDir string, hookType HookType) error {
	hookPath := filepath.Join(hookDir, string(hookType))

	if err := os.Remove(hookPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove hook file: %w", err)
	}

	slog.Debug("uninstalled hook", "path", hookPath)
	return nil
}

// GetHookDir returns the appropriate hooks directory.
// If global is true, returns ~/.git-hooks/, otherwise .git/hooks/
func GetHookDir(global bool) (string, error) {
	if global {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("failed to get home directory: %w", err)
		}
		return filepath.Join(home, ".git-hooks"), nil
	}

	return filepath.Join(".git", "hooks"), nil
}
