package git

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// HookType represents the type of git hook.
type HookType string

const (
	// HookUnknown is the zero value, meaning "not set".
	HookUnknown HookType = ""
	// PrepareCommitMsg runs before the commit message editor opens.
	PrepareCommitMsg HookType = "prepare-commit-msg"
	// CommitMsg runs after the message is authored and can veto the commit.
	CommitMsg HookType = "commit-msg"
)

// InstallHook installs a git hook that calls git-message.
// hookDir is typically .git/hooks or a global hooks directory.
// binaryPath is the absolute path to the gud binary, resolved at install time.
func InstallHook(hookDir string, hookType HookType, binaryPath string) error {
	hookPath := filepath.Join(hookDir, string(hookType))

	content := buildHookScript(binaryPath)

	//nolint:gosec // git hooks must be executable for git to invoke them
	if err := os.WriteFile(hookPath, []byte(content), 0755); err != nil {
		return fmt.Errorf("failed to write hook file: %w", err)
	}

	slog.Debug("installed hook", "path", hookPath, "type", hookType)

	return nil
}

// buildHookScript creates the hook script content using the full binary path
// so the hook works even if the binary is not on $PATH.
// The binary path is single-quoted and embedded single quotes are escaped
// to prevent shell injection via malicious binary paths.
func buildHookScript(binaryPath string) string {
	escaped := strings.ReplaceAll(binaryPath, "'", "'\\''")

	return `#!/bin/sh
# Auto-generated by gud
# Generates commit message based on staged changes

'` + escaped + `' hook run "$1"
`
}

// UninstallHook removes a git hook.
func UninstallHook(hookDir string, hookType HookType) error {
	hookPath := filepath.Join(hookDir, string(hookType))

	if err := os.Remove(hookPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove hook file: %w", err)
	}

	slog.Debug("uninstalled hook", "path", hookPath)

	return nil
}

// HookDir returns the appropriate hooks directory.
// If global is true, returns ~/.config/gud/hooks/ (gud's XDG config home,
// matching the global config location), otherwise .git/hooks/.
func HookDir(global bool) (string, error) {
	if global {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("failed to get home directory: %w", err)
		}

		return filepath.Join(home, ".config", "gud", "hooks"), nil
	}

	return filepath.Join(".git", "hooks"), nil
}

// GlobalHooksPath returns the global core.hooksPath configuration value,
// or an empty string when it is unset. Git does not automatically scan a
// custom global hooks directory, so hooks installed outside .git/hooks only
// run when core.hooksPath points at them.
func GlobalHooksPath(ctx context.Context) (string, error) {
	cmd := exec.CommandContext(ctx, "git", "config", "--global", "--get", "core.hooksPath")

	out, err := cmd.Output()
	if err != nil {
		// git exits 1 when the key is unset; treat that as empty.
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) && len(out) == 0 {
			return "", nil
		}

		return "", fmt.Errorf("read global core.hooksPath: %w", err)
	}

	return strings.TrimSpace(string(out)), nil
}

// SetGlobalHooksPath sets the global core.hooksPath configuration value.
func SetGlobalHooksPath(ctx context.Context, dir string) error {
	cmd := exec.CommandContext(ctx, "git", "config", "--global", "core.hooksPath", dir)
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("set global core.hooksPath: %w", err)
	}

	return nil
}

// UnsetGlobalHooksPath removes the global core.hooksPath configuration value.
// It is a no-op when the key is not set.
func UnsetGlobalHooksPath(ctx context.Context) error {
	cmd := exec.CommandContext(ctx, "git", "config", "--global", "--unset", "core.hooksPath")

	err := cmd.Run()
	if err != nil {
		// git exits 5 when the key is unset; uninstalling is idempotent.
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) && exitErr.ExitCode() == 5 {
			return nil
		}

		return fmt.Errorf("unset global core.hooksPath: %w", err)
	}

	return nil
}
