package request

import (
	"slices"
	"strings"
)

// This file holds the output sanitation applied to every model reply. It is
// deliberately separate from client.go: sanitation is a pure text transform
// with its own edge cases (fences, preambles, delimiter tails), so keeping it
// apart keeps the client focused on transport, retry, and verification.

// sanitizeOutput cleans AI-generated text.
func sanitizeOutput(text string) string {
	text = strings.TrimSpace(text)
	if text == "" {
		return text
	}

	text = extractFromCodeFences(text)
	text = stripPreamble(text)
	text = stripAfterDelimiter(text)

	return strings.TrimSpace(text)
}

// extractFromCodeFences unwraps a message the model wrapped in a markdown code
// fence, or in bare backticks, leaving only the message body.
func extractFromCodeFences(text string) string {
	lines := strings.Split(text, "\n")

	if len(lines) > 1 && strings.HasPrefix(strings.TrimSpace(lines[0]), "```") {
		for i := len(lines) - 1; i > 0; i-- {
			if strings.TrimSpace(lines[i]) == "```" {
				return strings.Join(lines[1:i], "\n")
			}
		}

		return strings.Join(lines[1:], "\n")
	}

	if strings.HasPrefix(text, "`") && strings.HasSuffix(text, "`") {
		inner := text[1 : len(text)-1]
		if !strings.Contains(inner, "`") {
			return inner
		}
	}

	return text
}

// preamblePrefixes are the openers a model may emit before the commit message
// itself. Matching is case-insensitive and happens repeatedly, since a model
// can nest them ("Here's the commit message:\n\nCommit message:\n\n<msg>").
var preamblePrefixes = []string{
	"here is your commit message",
	"here's the commit message",
	"here is the generated commit message",
	"generated commit message",
	"here is the commit",
	"here's your commit",
	"commit message:",
	"the commit message:",
	"generated message:",
	"output:",
	"result:",
}

// stripPreamble removes leading opener lines until the first line is not a
// recognised preamble.
func stripPreamble(text string) string {
	for {
		lines := strings.SplitN(text, "\n", 2)
		if len(lines) < 2 {
			return text
		}

		if !isPreambleLine(lines[0]) {
			return text
		}

		text = strings.TrimSpace(lines[1])
	}
}

// isPreambleLine reports whether line opens with a known preamble phrase.
func isPreambleLine(line string) bool {
	lower := strings.ToLower(strings.TrimSpace(line))

	return slices.ContainsFunc(preamblePrefixes, func(prefix string) bool {
		return strings.HasPrefix(lower, prefix)
	})
}

// stripAfterDelimiter removes AI trailing commentary that follows a separator
// line (---, ___, ***). It scans from the end and only cuts at a separator
// when the trailing content looks like short commentary; a legitimate commit
// body that happens to contain such a separator line is preserved.
func stripAfterDelimiter(text string) string {
	lines := strings.Split(text, "\n")

	for i := range slices.Backward(lines) {
		if !isDelimiterLine(lines[i]) {
			continue
		}

		// Only treat this separator as a delimiter if everything after it is
		// short commentary. Substantive body text after a --- line is kept.
		if isShortCommentaryTail(lines[i+1:]) {
			return strings.TrimSpace(strings.Join(lines[:i], "\n"))
		}
	}

	return text
}

// isDelimiterLine reports whether line is one of the separators a model uses to
// mark the end of its answer.
func isDelimiterLine(line string) bool {
	switch strings.TrimSpace(line) {
	case "---", "___", "***":
		return true
	default:
		return false
	}
}

// maxCommentaryLines and maxCommentaryTotal bound what stripAfterDelimiter
// considers AI trailing commentary rather than a commit body. AI commentary
// after a separator is at most a couple of short lines ("Generated by AI");
// anything longer — more lines or a body-sized block — is treated as commit
// content and preserved. Blank lines are allowed: a separator followed by a
// blank line then a short note ("---\n\nGenerated by AI") is still
// commentary, while substantive bodies exceed the length bound.
const (
	maxCommentaryLines = 2
	maxCommentaryTotal = 60
)

// isShortCommentaryTail reports whether the lines after a separator look like
// AI trailing commentary: at most a couple of lines totalling a small amount
// of text. A longer or multi-line block is treated as commit body content.
func isShortCommentaryTail(lines []string) bool {
	nonBlank, total := 0, 0

	for _, line := range lines {
		if line = strings.TrimSpace(line); line == "" {
			continue
		}

		nonBlank++
		total += len(line)

		if nonBlank > maxCommentaryLines {
			return false
		}
	}

	return total <= maxCommentaryTotal
}
